/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSetupRouteImport } from './routes/_authenticated/setup'
import { Route as AuthenticatedMastersRouteImport } from './routes/_authenticated/masters'
import { Route as AuthenticatedWorkersIndexRouteImport } from './routes/_authenticated/workers.index'
import { Route as AuthenticatedSalesIndexRouteImport } from './routes/_authenticated/sales.index'
import { Route as AuthenticatedPurchasesIndexRouteImport } from './routes/_authenticated/purchases.index'
import { Route as AuthenticatedWorkersSalaryRouteImport } from './routes/_authenticated/workers.salary'
import { Route as AuthenticatedWorkersAdvanceRouteImport } from './routes/_authenticated/workers.advance'
import { Route as AuthenticatedSalesNewRouteImport } from './routes/_authenticated/sales.new'
import { Route as AuthenticatedPurchasesNewRouteImport } from './routes/_authenticated/purchases.new'
import { Route as AuthenticatedVendorsVendorIdLedgerRouteImport } from './routes/_authenticated/vendors.$vendorId.ledger'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSetupRoute = AuthenticatedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMastersRoute = AuthenticatedMastersRouteImport.update({
  id: '/masters',
  path: '/masters',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkersIndexRoute =
  AuthenticatedWorkersIndexRouteImport.update({
    id: '/workers/',
    path: '/workers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesIndexRoute = AuthenticatedSalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPurchasesIndexRoute =
  AuthenticatedPurchasesIndexRouteImport.update({
    id: '/purchases/',
    path: '/purchases/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkersSalaryRoute =
  AuthenticatedWorkersSalaryRouteImport.update({
    id: '/workers/salary',
    path: '/workers/salary',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkersAdvanceRoute =
  AuthenticatedWorkersAdvanceRouteImport.update({
    id: '/workers/advance',
    path: '/workers/advance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesNewRoute = AuthenticatedSalesNewRouteImport.update({
  id: '/sales/new',
  path: '/sales/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPurchasesNewRoute =
  AuthenticatedPurchasesNewRouteImport.update({
    id: '/purchases/new',
    path: '/purchases/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorsVendorIdLedgerRoute =
  AuthenticatedVendorsVendorIdLedgerRouteImport.update({
    id: '/vendors/$vendorId/ledger',
    path: '/vendors/$vendorId/ledger',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/masters': typeof AuthenticatedMastersRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/purchases/new': typeof AuthenticatedPurchasesNewRoute
  '/sales/new': typeof AuthenticatedSalesNewRoute
  '/workers/advance': typeof AuthenticatedWorkersAdvanceRoute
  '/workers/salary': typeof AuthenticatedWorkersSalaryRoute
  '/purchases/': typeof AuthenticatedPurchasesIndexRoute
  '/sales/': typeof AuthenticatedSalesIndexRoute
  '/workers/': typeof AuthenticatedWorkersIndexRoute
  '/vendors/$vendorId/ledger': typeof AuthenticatedVendorsVendorIdLedgerRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/masters': typeof AuthenticatedMastersRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/': typeof AuthenticatedIndexRoute
  '/purchases/new': typeof AuthenticatedPurchasesNewRoute
  '/sales/new': typeof AuthenticatedSalesNewRoute
  '/workers/advance': typeof AuthenticatedWorkersAdvanceRoute
  '/workers/salary': typeof AuthenticatedWorkersSalaryRoute
  '/purchases': typeof AuthenticatedPurchasesIndexRoute
  '/sales': typeof AuthenticatedSalesIndexRoute
  '/workers': typeof AuthenticatedWorkersIndexRoute
  '/vendors/$vendorId/ledger': typeof AuthenticatedVendorsVendorIdLedgerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/masters': typeof AuthenticatedMastersRoute
  '/_authenticated/setup': typeof AuthenticatedSetupRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/purchases/new': typeof AuthenticatedPurchasesNewRoute
  '/_authenticated/sales/new': typeof AuthenticatedSalesNewRoute
  '/_authenticated/workers/advance': typeof AuthenticatedWorkersAdvanceRoute
  '/_authenticated/workers/salary': typeof AuthenticatedWorkersSalaryRoute
  '/_authenticated/purchases/': typeof AuthenticatedPurchasesIndexRoute
  '/_authenticated/sales/': typeof AuthenticatedSalesIndexRoute
  '/_authenticated/workers/': typeof AuthenticatedWorkersIndexRoute
  '/_authenticated/vendors/$vendorId/ledger': typeof AuthenticatedVendorsVendorIdLedgerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/masters'
    | '/setup'
    | '/purchases/new'
    | '/sales/new'
    | '/workers/advance'
    | '/workers/salary'
    | '/purchases/'
    | '/sales/'
    | '/workers/'
    | '/vendors/$vendorId/ledger'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/masters'
    | '/setup'
    | '/'
    | '/purchases/new'
    | '/sales/new'
    | '/workers/advance'
    | '/workers/salary'
    | '/purchases'
    | '/sales'
    | '/workers'
    | '/vendors/$vendorId/ledger'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/masters'
    | '/_authenticated/setup'
    | '/_authenticated/'
    | '/_authenticated/purchases/new'
    | '/_authenticated/sales/new'
    | '/_authenticated/workers/advance'
    | '/_authenticated/workers/salary'
    | '/_authenticated/purchases/'
    | '/_authenticated/sales/'
    | '/_authenticated/workers/'
    | '/_authenticated/vendors/$vendorId/ledger'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/setup': {
      id: '/_authenticated/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthenticatedSetupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/masters': {
      id: '/_authenticated/masters'
      path: '/masters'
      fullPath: '/masters'
      preLoaderRoute: typeof AuthenticatedMastersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workers/': {
      id: '/_authenticated/workers/'
      path: '/workers'
      fullPath: '/workers/'
      preLoaderRoute: typeof AuthenticatedWorkersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/': {
      id: '/_authenticated/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof AuthenticatedSalesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchases/': {
      id: '/_authenticated/purchases/'
      path: '/purchases'
      fullPath: '/purchases/'
      preLoaderRoute: typeof AuthenticatedPurchasesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workers/salary': {
      id: '/_authenticated/workers/salary'
      path: '/workers/salary'
      fullPath: '/workers/salary'
      preLoaderRoute: typeof AuthenticatedWorkersSalaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workers/advance': {
      id: '/_authenticated/workers/advance'
      path: '/workers/advance'
      fullPath: '/workers/advance'
      preLoaderRoute: typeof AuthenticatedWorkersAdvanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/new': {
      id: '/_authenticated/sales/new'
      path: '/sales/new'
      fullPath: '/sales/new'
      preLoaderRoute: typeof AuthenticatedSalesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchases/new': {
      id: '/_authenticated/purchases/new'
      path: '/purchases/new'
      fullPath: '/purchases/new'
      preLoaderRoute: typeof AuthenticatedPurchasesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendors/$vendorId/ledger': {
      id: '/_authenticated/vendors/$vendorId/ledger'
      path: '/vendors/$vendorId/ledger'
      fullPath: '/vendors/$vendorId/ledger'
      preLoaderRoute: typeof AuthenticatedVendorsVendorIdLedgerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMastersRoute: typeof AuthenticatedMastersRoute
  AuthenticatedSetupRoute: typeof AuthenticatedSetupRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPurchasesNewRoute: typeof AuthenticatedPurchasesNewRoute
  AuthenticatedSalesNewRoute: typeof AuthenticatedSalesNewRoute
  AuthenticatedWorkersAdvanceRoute: typeof AuthenticatedWorkersAdvanceRoute
  AuthenticatedWorkersSalaryRoute: typeof AuthenticatedWorkersSalaryRoute
  AuthenticatedPurchasesIndexRoute: typeof AuthenticatedPurchasesIndexRoute
  AuthenticatedSalesIndexRoute: typeof AuthenticatedSalesIndexRoute
  AuthenticatedWorkersIndexRoute: typeof AuthenticatedWorkersIndexRoute
  AuthenticatedVendorsVendorIdLedgerRoute: typeof AuthenticatedVendorsVendorIdLedgerRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMastersRoute: AuthenticatedMastersRoute,
  AuthenticatedSetupRoute: AuthenticatedSetupRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPurchasesNewRoute: AuthenticatedPurchasesNewRoute,
  AuthenticatedSalesNewRoute: AuthenticatedSalesNewRoute,
  AuthenticatedWorkersAdvanceRoute: AuthenticatedWorkersAdvanceRoute,
  AuthenticatedWorkersSalaryRoute: AuthenticatedWorkersSalaryRoute,
  AuthenticatedPurchasesIndexRoute: AuthenticatedPurchasesIndexRoute,
  AuthenticatedSalesIndexRoute: AuthenticatedSalesIndexRoute,
  AuthenticatedWorkersIndexRoute: AuthenticatedWorkersIndexRoute,
  AuthenticatedVendorsVendorIdLedgerRoute:
    AuthenticatedVendorsVendorIdLedgerRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
